{{- if eq .Values.workload.type "CronJob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "application-chart.fullname" . }}
  labels:
    {{- include "application-chart.labels" . | nindent 4 }}
    {{- with .Values.cronjob.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.cronjob.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  suspend: {{ .Values.cronjob.suspend }}
  {{- with .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ . }}
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "application-chart.selectorLabels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- $container := dict "command" .Values.cronjob.command "args" .Values.cronjob.args "env" .Values.cronjob.env "envFrom" .Values.cronjob.envFrom "resources" .Values.cronjob.resources "ports" (list) -}}
          {{- include "application-chart.podSpec" (dict "root" . "container" $container "restartPolicy" .Values.cronjob.restartPolicy) | nindent 10 }}
{{- end }}

