{{- if eq .Values.workload.type "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "application-chart.fullname" . }}
  labels:
    {{- include "application-chart.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "application-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "application-chart.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.configMap.enabled .Values.secret.enabled }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.configMap.enabled }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- end }}
        {{- if .Values.secret.enabled }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- end }}
      {{- end }}
    spec:
      {{- include "application-chart.podSpec" (dict "root" . "restartPolicy" "Always") | nindent 6 }}
{{- end }}
