{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "application-chart.fullname" . }}
  labels:
    {{- include "application-chart.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "externalSecret.secretStoreRef.name is required" .Values.externalSecret.secretStoreRef.name }}
    kind: {{ default "ClusterSecretStore" .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "application-chart.externalSecretTargetName" . }}
    creationPolicy: {{ default "Owner" .Values.externalSecret.target.creationPolicy }}
  {{- with .Values.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

